name: Sync documentation with Postman
on:
  pull_request:
    branches: [ "main" ]
    types:
      - closed
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-docs-with-postman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Build the Docker
        run: docker-compose up -d

      - name: Generate Open Api Specification - openapi.json
        run: bash ./gradlew clean generateOpenApiDocs

      - name: Install openapi-to-postmanv2 lib
        run: npm install -g openapi-to-postmanv2

      - name: Generate Postman Collection Json file from Open Api Specification
        run: |
         openapi2postmanv2 -s build/openapi.json -o build/collection.json -p -O folderStrategy=Tags,requestParametersResolution=Example,alwaysInheritAuthentication=true

      - name: Add pre-request script to collection
        run: |
         cat <<< $(jq --argjson event "$(<postman/pre-request-script.json)" '. += {$event} | {collection: .}' build/collection.json ) > out.json

      - name: Update Collection through Postman API
        run: |
         curl --location --request PUT '${{ secrets.POSTMAN_UPDATE_COLLECTION_URL }}' \
          --header 'Content-Type: application/json' \
          --header 'X-API-Key: ${{ secrets.POSTMAN_API_KEY }}' \
          --data @out.json

